In [1]:
import pandas as pd
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk','the glass of juice','the cup of tea','i am a good boy','i am a good developer','understand the meaning of words','your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
voc_size=10000

onehot_rep=[one_hot(words,voc_size)for words in sent]
onehot_rep

[[4599, 7165, 5463, 3737],
 [4599, 7165, 5463, 2621],
 [4599, 7971, 5463, 7390],
 [7597, 1798, 938, 5122, 6871],
 [7597, 1798, 938, 5122, 3709],
 [5770, 4599, 8410, 5463, 2216],
 [1247, 8403, 5431, 5122]]

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
# padding (make sentence of same length)
# pre --> zeros at starting
sent_length=8
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 4599, 7165, 5463, 3737],
       [   0,    0,    0,    0, 4599, 7165, 5463, 2621],
       [   0,    0,    0,    0, 4599, 7971, 5463, 7390],
       [   0,    0,    0, 7597, 1798,  938, 5122, 6871],
       [   0,    0,    0, 7597, 1798,  938, 5122, 3709],
       [   0,    0,    0, 5770, 4599, 8410, 5463, 2216],
       [   0,    0,    0,    0, 1247, 8403, 5431, 5122]])

In [12]:
dim=10 # feature representation one word is rep by 10 
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 79ms/step


array([[[-0.00712472, -0.04284728,  0.00536402,  0.04463783,
         -0.00577689, -0.03441917,  0.00107818, -0.00395368,
         -0.04168296,  0.04989405],
        [-0.00712472, -0.04284728,  0.00536402,  0.04463783,
         -0.00577689, -0.03441917,  0.00107818, -0.00395368,
         -0.04168296,  0.04989405],
        [-0.00712472, -0.04284728,  0.00536402,  0.04463783,
         -0.00577689, -0.03441917,  0.00107818, -0.00395368,
         -0.04168296,  0.04989405],
        [-0.00712472, -0.04284728,  0.00536402,  0.04463783,
         -0.00577689, -0.03441917,  0.00107818, -0.00395368,
         -0.04168296,  0.04989405],
        [-0.04636524, -0.00121427,  0.00083979, -0.03050612,
          0.02357305,  0.03567458, -0.02988395, -0.02151408,
         -0.02351304, -0.00368778],
        [ 0.01418868, -0.01595311, -0.00765532,  0.02704883,
          0.02786542,  0.04026839, -0.02674429,  0.02037602,
         -0.00136396,  0.0288839 ],
        [-0.00228073,  0.0473997 ,  0.0452236 , -0.0

In [10]:
embedded_docs[0]

array([   0,    0,    0,    0, 9689, 6679, 4858, 7375])

In [11]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 31ms/step


array([[-0.00712472, -0.04284728,  0.00536402,  0.04463783, -0.00577689,
        -0.03441917,  0.00107818, -0.00395368, -0.04168296,  0.04989405],
       [-0.00712472, -0.04284728,  0.00536402,  0.04463783, -0.00577689,
        -0.03441917,  0.00107818, -0.00395368, -0.04168296,  0.04989405],
       [-0.00712472, -0.04284728,  0.00536402,  0.04463783, -0.00577689,
        -0.03441917,  0.00107818, -0.00395368, -0.04168296,  0.04989405],
       [-0.00712472, -0.04284728,  0.00536402,  0.04463783, -0.00577689,
        -0.03441917,  0.00107818, -0.00395368, -0.04168296,  0.04989405],
       [-0.04636524, -0.00121427,  0.00083979, -0.03050612,  0.02357305,
         0.03567458, -0.02988395, -0.02151408, -0.02351304, -0.00368778],
       [ 0.01418868, -0.01595311, -0.00765532,  0.02704883,  0.02786542,
         0.04026839, -0.02674429,  0.02037602, -0.00136396,  0.0288839 ],
       [-0.00228073,  0.0473997 ,  0.0452236 , -0.03135502,  0.0299584 ,
        -0.03267376, -0.0192603 ,  0.00972987